// Order is significant
// Is ordered so that the cultural collision is viewable ASAP,
// which means we emphasize continuity and visual saliency
const countries = [
    "United States",
    "Canada",
    "Greenland",
    "Mexico",
    "Russia",
    "China",
    "Mongolia",
    "Kazakhstan",
    "Finland",
    "Brazil",
    "Bolivia",
    "Paraguay",
    "Argentina",
    "Chile",
    "Peru",
    "Colombia",
    "Australia",
    "Democratic Republic of the Congo",
    "Tanzania",
    "Angola",
    "Central African Republic",
    "Chad",
    "South Sudan",
    "Sudan",

    "Afghanistan",
    "Åland Islands",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Armenia",
    "Aruba",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Caribbean Netherlands Bonaire, Sint Eustatius and Saba",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "British Indian Ocean Territory",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cape Verde Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Cayman Islands",
    "Christmas Island",
    "Cocos Keeling Islands",
    "Comoros",
    "Republic of the Congo",
    "Cook Islands",
    "Costa Rica",
    "Ivory Coast Côte d'Ivoire",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czech Republic Czechia",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "The Gambia Gambia",
    "Georgia country",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Vatican City Holy See",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kenya",
    "Kiribati",
    "North Korea",
    "South Korea, Republic of",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau Macao",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Philippines",
    "Pitcairn Islands Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Réunion",
    "Romania",
    "Rwanda",
    "Saint Barthélemy",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Martin Saint Martin French part",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "São Tomé and Príncipe Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten Sint Maarten Dutch part",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "Spain",
    "Sri Lanka",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Thailand",
    "East Timor Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States Minor Outlying Islands",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam Viet Nam",
    "British Virgin",
    "United States Virgin Islands",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]


const countryCodes = {
    "Afghanistan"                                            : "AFG",
    "Åland Islands"                                          : "ALA",
    "Albania"                                                : "ALB",
    "Algeria"                                                : "DZA",
    "American Samoa"                                         : "ASM",
    "Andorra"                                                : "AND",
    "Angola"                                                 : "AGO",
    "Anguilla"                                               : "AIA",
    "Antarctica"                                             : "ATA",
    "Antigua and Barbuda"                                    : "ATG",
    "Argentina"                                              : "ARG",
    "Armenia"                                                : "ARM",
    "Aruba"                                                  : "ABW",
    "Australia"                                              : "AUS",
    "Austria"                                                : "AUT",
    "Azerbaijan"                                             : "AZE",
    "Bahamas"                                                : "BHS",
    "Bahrain"                                                : "BHR",
    "Bangladesh"                                             : "BGD",
    "Barbados"                                               : "BRB",
    "Belarus"                                                : "BLR",
    "Belgium"                                                : "BEL",
    "Belize"                                                 : "BLZ",
    "Benin"                                                  : "BEN",
    "Bermuda"                                                : "BMU",
    "Bhutan"                                                 : "BTN",
    "Bolivia"                                                : "BOL",
    "Caribbean Netherlands Bonaire, Sint Eustatius and Saba" : "BES",
    "Bosnia and Herzegovina"                                 : "BIH",
    "Botswana"                                               : "BWA",
    "Bouvet Island"                                          : "BVT",
    "Brazil"                                                 : "BRA",
    "British Indian Ocean Territory"                         : "IOT",
    "Brunei Darussalam"                                      : "BRN",
    "Bulgaria"                                               : "BGR",
    "Burkina Faso"                                           : "BFA",
    "Burundi"                                                : "BDI",
    "Cape Verde Cabo Verde"                                  : "CPV",
    "Cambodia"                                               : "KHM",
    "Cameroon"                                               : "CMR",
    "Canada"                                                 : "CAN",
    "Cayman Islands"                                         : "CYM",
    "Central African Republic"                               : "CAF",
    "Chad"                                                   : "TCD",
    "Chile"                                                  : "CHL",
    "China"                                                  : "CHN",
    "Christmas Island"                                       : "CXR",
    "Cocos Keeling Islands"                                  : "CCK",
    "Colombia"                                               : "COL",
    "Comoros"                                                : "COM",
    "Republic of the Congo"                                  : "COG",
    "Democratic Republic of the Congo"                       : "COD",
    "Cook Islands"                                           : "COK",
    "Costa Rica"                                             : "CRI",
    "Ivory Coast Côte d'Ivoire"                              : "CIV",
    "Croatia"                                                : "HRV",
    "Cuba"                                                   : "CUB",
    "Curaçao"                                                : "CUW",
    "Cyprus"                                                 : "CYP",
    "Czech Republic Czechia"                                 : "CZE",
    "Denmark"                                                : "DNK",
    "Djibouti"                                               : "DJI",
    "Dominica"                                               : "DMA",
    "Dominican Republic"                                     : "DOM",
    "Ecuador"                                                : "ECU",
    "Egypt"                                                  : "EGY",
    "El Salvador"                                            : "SLV",
    "Equatorial Guinea"                                      : "GNQ",
    "Eritrea"                                                : "ERI",
    "Estonia"                                                : "EST",
    "Eswatini"                                               : "SWZ",
    "Ethiopia"                                               : "ETH",
    "Falkland Islands"                                       : "FLK",
    "Faroe Islands"                                          : "FRO",
    "Fiji"                                                   : "FJI",
    "Finland"                                                : "FIN",
    "France"                                                 : "FRA",
    "French Guiana"                                          : "GUF",
    "French Polynesia"                                       : "PYF",
    "French Southern Territories"                            : "ATF",
    "Gabon"                                                  : "GAB",
    "The Gambia Gambia"                                      : "GMB",
    "Georgia country"                                        : "GEO",
    "Germany"                                                : "DEU",
    "Ghana"                                                  : "GHA",
    "Gibraltar"                                              : "GIB",
    "Greece"                                                 : "GRC",
    "Greenland"                                              : "GRL",
    "Grenada"                                                : "GRD",
    "Guadeloupe"                                             : "GLP",
    "Guam"                                                   : "GUM",
    "Guatemala"                                              : "GTM",
    "Guernsey"                                               : "GGY",
    "Guinea"                                                 : "GIN",
    "Guinea-Bissau"                                          : "GNB",
    "Guyana"                                                 : "GUY",
    "Haiti"                                                  : "HTI",
    "Heard Island and McDonald Islands"                      : "HMD",
    "Vatican City Holy See"                                  : "VAT",
    "Honduras"                                               : "HND",
    "Hong Kong"                                              : "HKG",
    "Hungary"                                                : "HUN",
    "Iceland"                                                : "ISL",
    "India"                                                  : "IND",
    "Indonesia"                                              : "IDN",
    "Iran"                                                   : "IRN",
    "Iraq"                                                   : "IRQ",
    "Ireland"                                                : "IRL",
    "Isle of Man"                                            : "IMN",
    "Israel"                                                 : "ISR",
    "Italy"                                                  : "ITA",
    "Jamaica"                                                : "JAM",
    "Japan"                                                  : "JPN",
    "Jersey"                                                 : "JEY",
    "Jordan"                                                 : "JOR",
    "Kazakhstan"                                             : "KAZ",
    "Kenya"                                                  : "KEN",
    "Kiribati"                                               : "KIR",
    "North Korea"                                            : "PRK",
    "South Korea, Republic of"                               : "KOR",
    "Kuwait"                                                 : "KWT",
    "Kyrgyzstan"                                             : "KGZ",
    "Laos"                                                   : "LAO",
    "Latvia"                                                 : "LVA",
    "Lebanon"                                                : "LBN",
    "Lesotho"                                                : "LSO",
    "Liberia"                                                : "LBR",
    "Libya"                                                  : "LBY",
    "Liechtenstein"                                          : "LIE",
    "Lithuania"                                              : "LTU",
    "Luxembourg"                                             : "LUX",
    "Macau Macao"                                            : "MAC",
    "Macedonia"                                              : "MKD",
    "Madagascar"                                             : "MDG",
    "Malawi"                                                 : "MWI",
    "Malaysia"                                               : "MYS",
    "Maldives"                                               : "MDV",
    "Mali"                                                   : "MLI",
    "Malta"                                                  : "MLT",
    "Marshall Islands"                                       : "MHL",
    "Martinique"                                             : "MTQ",
    "Mauritania"                                             : "MRT",
    "Mauritius"                                              : "MUS",
    "Mayotte"                                                : "MYT",
    "Mexico"                                                 : "MEX",
    "Micronesia"                                             : "FSM",
    "Moldova"                                                : "MDA",
    "Monaco"                                                 : "MCO",
    "Mongolia"                                               : "MNG",
    "Montenegro"                                             : "MNE",
    "Montserrat"                                             : "MSR",
    "Morocco"                                                : "MAR",
    "Mozambique"                                             : "MOZ",
    "Myanmar"                                                : "MMR",
    "Namibia"                                                : "NAM",
    "Nauru"                                                  : "NRU",
    "Nepal"                                                  : "NPL",
    "Netherlands"                                            : "NLD",
    "New Caledonia"                                          : "NCL",
    "New Zealand"                                            : "NZL",
    "Nicaragua"                                              : "NIC",
    "Niger"                                                  : "NER",
    "Nigeria"                                                : "NGA",
    "Niue"                                                   : "NIU",
    "Norfolk Island"                                         : "NFK",
    "Northern Mariana Islands"                               : "MNP",
    "Norway"                                                 : "NOR",
    "Oman"                                                   : "OMN",
    "Pakistan"                                               : "PAK",
    "Palau"                                                  : "PLW",
    "Palestine"                                              : "PSE",
    "Panama"                                                 : "PAN",
    "Papua New Guinea"                                       : "PNG",
    "Paraguay"                                               : "PRY",
    "Peru"                                                   : "PER",
    "Philippines"                                            : "PHL",
    "Pitcairn Islands Pitcairn"                              : "PCN",
    "Poland"                                                 : "POL",
    "Portugal"                                               : "PRT",
    "Puerto Rico"                                            : "PRI",
    "Qatar"                                                  : "QAT",
    "Réunion"                                                : "REU",
    "Romania"                                                : "ROU",
    "Russia"                                                 : "RUS",
    "Rwanda"                                                 : "RWA",
    "Saint Barthélemy"                                       : "BLM",
    "Saint Helena, Ascension and Tristan da Cunha"           : "SHN",
    "Saint Kitts and Nevis"                                  : "KNA",
    "Saint Lucia"                                            : "LCA",
    "Martin Saint Martin French part"                        : "MAF",
    "Saint Pierre and Miquelon"                              : "SPM",
    "Saint Vincent and the Grenadines"                       : "VCT",
    "Samoa"                                                  : "WSM",
    "San Marino"                                             : "SMR",
    "São Tomé and Príncipe Sao Tome and Principe"            : "STP",
    "Saudi Arabia"                                           : "SAU",
    "Senegal"                                                : "SEN",
    "Serbia"                                                 : "SRB",
    "Seychelles"                                             : "SYC",
    "Sierra Leone"                                           : "SLE",
    "Singapore"                                              : "SGP",
    "Sint Maarten Sint Maarten Dutch part"                   : "SXM",
    "Slovakia"                                               : "SVK",
    "Slovenia"                                               : "SVN",
    "Solomon Islands"                                        : "SLB",
    "Somalia"                                                : "SOM",
    "South Africa"                                           : "ZAF",
    "South Georgia and the South Sandwich Islands"           : "SGS",
    "South Sudan"                                            : "SSD",
    "Spain"                                                  : "ESP",
    "Sri Lanka"                                              : "LKA",
    "Sudan"                                                  : "SDN",
    "Suriname"                                               : "SUR",
    "Svalbard and Jan Mayen"                                 : "SJM",
    "Sweden"                                                 : "SWE",
    "Switzerland"                                            : "CHE",
    "Syria"                                                  : "SYR",
    "Taiwan"                                                 : "TWN",
    "Tajikistan"                                             : "TJK",
    "Tanzania"                                               : "TZA",
    "Thailand"                                               : "THA",
    "East Timor Timor-Leste"                                 : "TLS",
    "Togo"                                                   : "TGO",
    "Tokelau"                                                : "TKL",
    "Tonga"                                                  : "TON",
    "Trinidad and Tobago"                                    : "TTO",
    "Tunisia"                                                : "TUN",
    "Turkey"                                                 : "TUR",
    "Turkmenistan"                                           : "TKM",
    "Turks and Caicos Islands"                               : "TCA",
    "Tuvalu"                                                 : "TUV",
    "Uganda"                                                 : "UGA",
    "Ukraine"                                                : "UKR",
    "United Arab Emirates"                                   : "ARE",
    "United Kingdom"                                         : "GBR",
    "United States"                                          : "USA",
    "United States Minor Outlying Islands"                   : "UMI",
    "Uruguay"                                                : "URY",
    "Uzbekistan"                                             : "UZB",
    "Vanuatu"                                                : "VUT",
    "Venezuela"                                              : "VEN",
    "Vietnam Viet Nam"                                       : "VNM",
    "British Virgin"                                         : "VGB",
    "United States Virgin Islands"                           : "VIR",
    "Wallis and Futuna"                                      : "WLF",
    "Western Sahara"                                         : "ESH",
    "Yemen"                                                  : "YEM",
    "Zambia"                                                 : "ZMB",
    "Zimbabwe"                                               : "ZWE",
};

